name: "General CI checks"

on:
  push:
  pull_request:

jobs:
  test-in-renode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run scripts in Renode
        uses: antmicro-labs/renode-linux-runner-action@v0-next-fix
        with:
          shared-dirs: ./
          renode-run: |
            ls /dev | grep video
          devices: vivid
