name: "General CI checks"

on:
  push:
  pull_request:

jobs:
  test-in-renode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run scripts in Renode
        uses: antmicro/renode-linux-runner-action@v0
        with:
          shared-dir: ./
          renode-run: |
            ls /dev | grep video
          devices: vivid
